apiVersion: v1
kind: Service
metadata:
  name: {{ include "tcp.fullname" . }}
  labels:
    {{- include "tcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
      {{- if and .Values.service.nodePort (eq "NodePort" .Values.service.type ) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "tcp.selectorLabels" . | nindent 4 }}
